Repository asagrekin/GamesInOne, pull requests merged in 2023-05, with the labels that each got.

#23 Database refactor merge
  src/database/README.md
  src/database/dbFiles/ind.dat
  src/database/dbFiles/lst.dat
  src/database/dbObjects.h
  src/database/example
  src/database/example.cpp
  src/database/example.o
  src/database/gamesDB.cpp
  src/database/gamesDB.h
  src/database/gamesDB.o
Labels: enhancement

#24 Testing ci include
  .github/workflows/main.yml
  reports/Week5Report.md
Labels: enhancement

#34 Bring Front-End back to main, already tested merge.
  src/backend/gamelauncher.cpp
  src/database/dbObjects.h
  src/database/gamesDB.cpp
  src/front-end/front-end-interface/AddGameScreen.cs
  src/front-end/front-end-interface/GameRow.Designer.cs
  src/front-end/front-end-interface/GameRow.cs
  src/front-end/front-end-interface/GamesInOne.csproj
  src/front-end/front-end-interface/GamesInOne.sln
  src/front-end/front-end-interface/MainScreen.Designer.cs
  src/front-end/front-end-interface/MainScreen.cs
  src/front-end/front-end-interface/Properties/Resources.Designer.cs
  src/front-end/front-end-interface/Properties/Resources.resx
  src/front-end/front-end-interface/Resources/Logo.png
  src/front-end/front-end-test/FrontEndTest.csproj
  src/front-end/link-front-and-back/LinkFrontAndBack.cpp
  src/front-end/link-front-and-back/LinkFrontAndBack.h
  src/front-end/link-front-and-back/LinkFrontAndBack.vcxproj
  src/front-end/link-front-and-back/LinkFrontAndBack.vcxproj.filters
Labels: documentation, enhancement

#36 Added default image capability merge
  src/front-end/front-end-interface/AddGameScreen.Designer.cs
  src/front-end/front-end-interface/AddGameScreen.cs
  src/front-end/front-end-interface/GameRow.Designer.cs
  src/front-end/front-end-interface/GamesInOne.csproj
  src/front-end/front-end-interface/Properties/Resources.Designer.cs
  src/front-end/front-end-interface/Properties/Resources.resx
  src/front-end/front-end-interface/Resources/game_placeholder.png
Labels: enhancement

#44 Merging the Week 9 Report into main
  reports/Week9Report.md
Labels: documentation

#48 Create a bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#49 Merging Button and CI documentation
  README.md
  resources/add_game_page.png
  resources/change_order_page.png
  resources/main_page.png
Labels: documentation

#54 Added Backend README File
  src/backend/README.md
Labels: documentation

#56 Merge front-end to main: Added more documentations, and add status feature.
  README.md
  src/front-end/README.md
  src/front-end/front-end-interface/AddGameScreen.Designer.cs
  src/front-end/front-end-interface/AddGameScreen.cs
  src/front-end/front-end-interface/GameRow.cs
  src/front-end/front-end-interface/GamesEditList.cs
  src/front-end/front-end-interface/MainScreen.Designer.cs
  src/front-end/front-end-interface/MainScreen.cs
  src/front-end/front-end-test/FrontEndUnitTest.cs
  src/front-end/link-front-and-back/LinkFrontAndBack.cpp
  src/front-end/link-front-and-back/LinkFrontAndBack.h
Labels: documentation, enhancement

#67 documented backend functionalities to the demo
  src/backend/demo.cpp
Labels: documentation

#68 Got rid of commented out code in dbObjects.h
  src/database/dbObjects.h
Labels: documentation

#69 Ci tests so that you can run one at a time based on what you changed in the repo.
  .github/workflows/backend-test.yml
  .github/workflows/front-end-test.yml
  README.md
  src/backend/README.md
  src/front-end/README.md
Labels: enhancement

#70 Updated to version 1.1 from beta
  README.md
Labels: documentation

#71 Week 10 Report Addition
  reports/Week10Report.md
Labels: documentation
